version: '3.5'

services:
  db_auth: 
    container_name: db_auth
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:15.2-alpine3.17
    volumes:
      - db_auth_vol:/var/lib/postgressql/data/

volumes:
  db_auth_vol: {}
