name: auth
description: Auth Service
version: 1.0.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  conduit: ^4.3.9
  conduit_core: ^4.3.8
  conduit_postgresql: ^4.3.7
  jaguar_jwt: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
